### ISSUE TITLE
[Bug]: OAS Parameter $ref not expanding in path, not being registered as variable

### ISSUE THREAD

**Issue by dave-apisec** [apisec-inc/Support#89]
### Severity

Blocker

### What happened?

When onboarding an OAS file, there are parameters that reference definitions later in the file using $ref

Swagger Doc $ref:
https://swagger.io/docs/specification/using-ref/

Please reach out to me and I'll provide full swagger.

Example swagger snippet:
```
paths:
  /api/v1/{country}/list
      parameters:
        - $ref: '#/components/parameters/country'
```

and later in the file 

```
components:
  parameters:
    country:
      name: country
      in: path
      required: true
      schema:
        type: string
        enum:
          - US
          - CA
          - IN
          - UK
```

Expected:
APIsec expands these references and creates variables (and as a result, playbooks to test) each of the different parameters referenced.

`URI: /api/v1/US/list`

Actual: 
The {parameter} value including curly braces is being inserted in the path, causing issues accessing these endpoints.

`URI: /api/v1/{country}/list` which is not a valid URI
